packages:
  - packages/*

catalogMode: prefer

catalog:
  "@biomejs/biome": ^1.8.3
  "@changesets/changelog-github": ^0.5.0
  "@changesets/cli": ^2.27.7
  "@storybook/addon-essentials": ~8.1.0
  "@storybook/addon-interactions": ~8.1.0
  "@storybook/addon-links": ~8.1.0
  "@storybook/blocks": ~8.1.0
  "@storybook/components": ^8.0.0
  "@storybook/core-events": ^8.0.0
  "@storybook/icons": ^1.2.9
  "@storybook/manager-api": ^8.0.0
  "@storybook/preview-api": ^8.0.0
  "@storybook/react": ~8.1.0
  "@storybook/react-vite": ~8.1.0
  "@storybook/test": ~8.1.0
  "@storybook/theming": ^8.0.0
  "@storybook/types": ^8.0.0
  "@types/node": ^20.14.9
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@vitejs/plugin-react": ^4.3.1
  npm-run-all: ^4.1.5
  storybook: ^8.0.0
  react: ^18.3.1
  react-dom: ^18.3.1
  tsup: ^8.1.0
  typescript: ^5.5.3
  vite: ^5.3.3
  zx: ^8.1.3
