packages:
  - packages/*

catalog:
  '@biomejs/biome': ~2.1.3
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.5
  '@storybook/addon-docs': ^9.1.1
  '@storybook/addon-links': ^9.1.1
  '@storybook/icons': ^1.4.0
  '@storybook/react-vite': ^9.1.1
  '@types/node': ^20.19.9
  '@types/react': ^18.3.3
  '@types/react-dom': ^18.3.0
  react: ^18.3.1
  react-dom: ^18.3.1
  storybook: ^9.1.1
  tsup: ^8.5.0
  typescript: ^5.9.2
  zx: ^8.8.0

catalogMode: prefer
