packages:
  - packages/*

catalog:
  '@biomejs/biome': ~2.3.1
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.7
  '@playwright/test': ^1.49.1
  '@storybook/addon-docs': ^10.0.0
  '@storybook/icons': ^1.4.0
  '@storybook/react-vite': ^10.0.0
  '@types/node': 20.19.9
  '@types/react': ^18.3.3
  '@types/react-dom': ^18.3.0
  react: ^18.3.1
  react-dom: ^18.3.1
  storybook: ^10.0.0
  tsup: ^8.5.0
  typescript: ^5.9.3
  zx: ^8.8.5

catalogMode: prefer
